### ISSUE TITLE
To-do stuff & public requests

### ISSUE THREAD

**Issue by TriForceX** [TriForceX/JediKnightLegacy#1]
The next list is a bunch of stuff that should/need to be ported from other mods, and also some other custom features that could be added:

## From JA+:
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

## From JAPro:
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

## Other features:
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

**Comment by miguelsotobaez** [comment]
**FROM JA+:**

- [ ] Duel Isolation
- [ ] Flipkicks without altering wall run
- [ ] Clan Tag Protection (for more than 1 clan will be awesome)
- [ ] Easy saber change without respawning
- [ ] Extended Melee attacks
